name: Deploy JavaDoc

on: 
 push:
  branches:
  - master
  - main
  
jobs:
  publish:
    runs-on: ubuntu-latest
    steps: 
     - name: Deploy JavaDoc 
     uses: Natalia25souza/Javadoc-publisher.static.yml
    with:
       GITHUB_TOKEN:
       javadoc-branch: javadoc
       java-version: 18
       target-folder: javadoc
       project: gradle
       custom-command: javadoc -d javadoc -sourcepath src/main/java -subpackages .
  
  
  
